//SESSIONS
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const ADD_STUDY_SESSION = 'ADD_STUDY_SESSION';
export const CURRENT_STUDY_SESSION = 'CURRENT_STUDY_SESSION';
export const DELETE_STUDY_SESSION = 'DELETE_STUDY_SESSION';

//NOTES
export const FETCH_NOTES = 'FETCH_NOTES';
export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const CURRENT_VIDEO = 'CURRENT_VIDEO';

//USER AUTH
export const GET_USER = "GET_USER";
export const REMOVE_USER = "REMOVE_USER";